apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yahoo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://your.git.repo.git
    targetRevision: HEAD
    path: prod
  destination:
    server: http://181.214.142.155:6443
    namespace: yahoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true